<?php

/** ============================================================================
 * Description
 * @package BootPress
 * @version <<version>>
 * -----
 * @author Sam Rankin <samrankin.dev@gmail.com>
 * @copyright Copyright (c) 2019 Your Company
 * -----
 * Created Date:  12-3-19
 * Last Modified: 12-3-19 at 11:18 am
 * Modified By:   Sam Rankin <samrankin.dev@gmail.com>
 * -----
 * HISTORY:
 * Date    	By	Comments
 * --------	--	--------------------------------------------------------------
 * =========================================================================== */

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_site_header',
        'title' => 'Site Header',
        'fields' => array(
            array(
                'key' => 'field_site_header',
                'label' => 'Site Header',
                'name' => 'site_header',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5de5914295c2e',
                        'label' => 'Content',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5ddd7d979b108',
                        'label' => 'Content',
                        'name' => 'rows',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ddd7da39b109',
                                'label' => 'Column',
                                'name' => 'columns',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 1,
                                'max' => 6,
                                'layout' => 'block',
                                'button_label' => 'Add Column',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ddd81ba6cd19',
                                        'label' => 'Content',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5ddd7dd99b10a',
                                        'label' => 'Content',
                                        'name' => 'content',
                                        'type' => 'flexible_content',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layouts' => array(
                                            'layout_5ddd7de5c6786' => array(
                                                'key' => 'layout_5ddd7de5c6786',
                                                'name' => 'logo',
                                                'label' => 'Logo',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7e9a9b111',
                                                        'label' => 'Logo Option',
                                                        'name' => 'logo_option',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'default' => 'Default',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            'layout_5ddd7dfa9b10b' => array(
                                                'key' => 'layout_5ddd7dfa9b10b',
                                                'name' => 'menu',
                                                'label' => 'Menu',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7eb99b112',
                                                        'label' => 'Menu',
                                                        'name' => 'menu',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            2 => 'Primary Navigation',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68f0d02bad',
                                                        'label' => 'Class',
                                                        'name' => 'class',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68f1902bae',
                                                        'label' => 'ID',
                                                        'name' => 'id',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68f1f02baf',
                                                        'label' => 'Container Tag',
                                                        'name' => 'container_tag',
                                                        'type' => 'button_group',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'div' => 'DIV',
                                                            'nav' => 'NAV',
                                                            'none' => 'NONE',
                                                        ),
                                                        'allow_null' => 0,
                                                        'default_value' => '',
                                                        'layout' => 'horizontal',
                                                        'return_format' => 'value',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68f9c02bb0',
                                                        'label' => 'Container Class',
                                                        'name' => 'container_class',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68fa402bb1',
                                                        'label' => 'Container ID',
                                                        'name' => 'container_id',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68fc902bb2',
                                                        'label' => 'Text Before Link',
                                                        'name' => 'before',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => 'Nav Link',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de6901e02bb4',
                                                        'label' => 'Text Before Link Text',
                                                        'name' => 'link_before',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => 'Link Text',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de6903c02bb5',
                                                        'label' => 'Text After Link Text',
                                                        'name' => 'link_after',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => 'Link Text',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5de68fde02bb3',
                                                        'label' => 'Text After Link',
                                                        'name' => 'after',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => 'Nav Link',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            'layout_5ddd7e019b10c' => array(
                                                'key' => 'layout_5ddd7e019b10c',
                                                'name' => 'widget_area',
                                                'label' => 'Widget Area',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7ee99b113',
                                                        'label' => 'Widget Area',
                                                        'name' => 'widget_area',
                                                        'type' => 'select',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'footer-1' => 'Footer Column 1',
                                                            'footer-2' => 'Footer Column 2',
                                                            'footer-3' => 'Footer Column 3',
                                                            'footer-4' => 'Footer Column 4',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 0,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            'layout_5ddd7e0b9b10d' => array(
                                                'key' => 'layout_5ddd7e0b9b10d',
                                                'name' => 'search',
                                                'label' => 'Search',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7efe9b114',
                                                        'label' => 'Add Search',
                                                        'name' => 'add_search',
                                                        'type' => 'true_false',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'message' => '',
                                                        'default_value' => 1,
                                                        'ui' => 1,
                                                        'ui_on_text' => '',
                                                        'ui_off_text' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '1',
                                            ),
                                            'layout_5ddd7e269b10e' => array(
                                                'key' => 'layout_5ddd7e269b10e',
                                                'name' => 'shortcode',
                                                'label' => 'Shortcode',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7f2e9b115',
                                                        'label' => 'Shortcode',
                                                        'name' => 'shortcode',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            'layout_5ddd7e309b10f' => array(
                                                'key' => 'layout_5ddd7e309b10f',
                                                'name' => 'text',
                                                'label' => 'Text',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7f399b116',
                                                        'label' => 'Text',
                                                        'name' => 'text',
                                                        'type' => 'text',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'default_value' => '',
                                                        'placeholder' => '',
                                                        'prepend' => '',
                                                        'append' => '',
                                                        'maxlength' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                            'layout_5ddd7e5f9b110' => array(
                                                'key' => 'layout_5ddd7e5f9b110',
                                                'name' => 'company_info',
                                                'label' => 'Company Info',
                                                'display' => 'block',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7f439b117',
                                                        'label' => 'Company Info',
                                                        'name' => 'company_info',
                                                        'type' => 'checkbox',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            'address' => 'Address',
                                                            'phone' => 'Phone',
                                                            'fax' => 'Fax',
                                                            'email' => 'Email',
                                                            'hob' => 'Business Hours',
                                                            'social' => 'Social Links',
                                                        ),
                                                        'allow_custom' => 0,
                                                        'default_value' => array(),
                                                        'layout' => 'horizontal',
                                                        'toggle' => 1,
                                                        'return_format' => 'value',
                                                        'save_custom' => 0,
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7fc19b118',
                                                        'label' => 'Add Icons',
                                                        'name' => 'add_icons',
                                                        'type' => 'true_false',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'message' => '',
                                                        'default_value' => 1,
                                                        'ui' => 1,
                                                        'ui_on_text' => '',
                                                        'ui_off_text' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7fd39b119',
                                                        'label' => 'Add Links',
                                                        'name' => 'add_links',
                                                        'type' => 'true_false',
                                                        'instructions' => '',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'message' => '',
                                                        'default_value' => 1,
                                                        'ui' => 1,
                                                        'ui_on_text' => '',
                                                        'ui_off_text' => '',
                                                    ),
                                                ),
                                                'min' => '',
                                                'max' => '',
                                            ),
                                        ),
                                        'button_label' => 'Add Content Block',
                                        'min' => '',
                                        'max' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ddd81ac6cd18',
                                        'label' => 'Styles',
                                        'name' => '',
                                        'type' => 'tab',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'placement' => 'top',
                                        'endpoint' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5de593b24373c',
                                        'label' => 'Styles',
                                        'name' => 'styles',
                                        'type' => 'group',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_5ddd7a7c9b0fd',
                                                'label' => 'Width',
                                                'name' => 'width',
                                                'type' => 'group',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'layout' => 'table',
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_5ddd7abb9b0fe',
                                                        'label' => 'XS Screen',
                                                        'name' => 'xs',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size less than 320px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7ba69b0ff',
                                                        'label' => 'SM Screen',
                                                        'name' => 'sm',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size 320px-576px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7bb69b101',
                                                        'label' => 'MS Screen',
                                                        'name' => 'ms',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size 577px-768px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7bc99b103',
                                                        'label' => 'MD Screen',
                                                        'name' => 'md',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size 769px-1024px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7bd39b104',
                                                        'label' => 'ML Screen',
                                                        'name' => 'ml',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size 1025px-1280px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7bde9b106',
                                                        'label' => 'LG Screen',
                                                        'name' => 'lg',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size 1281px-1440px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                    array(
                                                        'key' => 'field_5ddd7bea9b107',
                                                        'label' => 'XL Screen',
                                                        'name' => 'xl',
                                                        'type' => 'select',
                                                        'instructions' => 'Screen Size larger than 1440px',
                                                        'required' => 0,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'choices' => array(
                                                            12 => '12/12 Columns or Full Width',
                                                            11 => '11/12 Columns',
                                                            10 => '10/12 Columns or 5/6',
                                                            9 => '9/12 Columns or 3/4',
                                                            8 => '8/12 Columns or 2/3',
                                                            7 => '7/12 Columns',
                                                            6 => '6/12 Columns or 1/2',
                                                            5 => '5/12 Columns',
                                                            4 => '4/12 Columns or 1/3',
                                                            3 => '3/12 Columns or 1/4',
                                                            2 => '2/12 Columns or 1/6',
                                                            1 => '1/12 Columns',
                                                            'auto' => 'Automatic width based on column content',
                                                        ),
                                                        'default_value' => array(),
                                                        'allow_null' => 1,
                                                        'multiple' => 0,
                                                        'ui' => 0,
                                                        'return_format' => 'value',
                                                        'ajax' => 0,
                                                        'placeholder' => '',
                                                    ),
                                                ),
                                            ),
                                            array(
                                                'key' => 'field_5ddd83c5a64ae',
                                                'label' => 'Extra Classes',
                                                'name' => 'class',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5de5915095c2f',
                        'label' => 'Style',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5de5916595c30',
                        'label' => 'Style',
                        'name' => 'style',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5ddd80169b11a',
                                'label' => 'Background',
                                'name' => 'background',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5ddd80519b11b',
                                        'label' => 'Color Palette Color',
                                        'name' => 'color_palette_color',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'primary' => 'Primary',
                                            'secondary' => 'Secondary',
                                            'tertiary' => 'Tertiary',
                                            'success' => 'Success',
                                            'danger' => 'Danger',
                                            'warning' => 'Warning',
                                            'info' => 'Info',
                                            'light' => 'Light',
                                            'dark' => 'Dark',
                                            'custom' => 'Custom',
                                        ),
                                        'default_value' => array(),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'value',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ddd80ec9b11c',
                                        'label' => 'Custom Color',
                                        'name' => 'custom_color',
                                        'type' => 'color_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_5ddd80519b11b',
                                                    'operator' => '==',
                                                    'value' => 'custom',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                    ),
                                    array(
                                        'key' => 'field_5ddd810b9b11d',
                                        'label' => 'Color Opacity',
                                        'name' => 'color_opacity',
                                        'type' => 'number',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => 100,
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '%',
                                        'min' => 0,
                                        'max' => 100,
                                        'step' => 1,
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-header',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
